export const ActionTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    FETCH_TRACK_REQUEST: 'FETCH_TRACK_REQUEST',
    FETCH_TRACK_SUCCESS: 'FETCH_TRACK_SUCCESS',
    FETCH_TRACKPART_SUCCESS: 'FETCH_TRACKPART_SUCCESS',
    FETCH_TRACK_FAILURE: 'FETCH_TRACK_FAILURE',

    FETCH_DEVICES_REQUEST: 'FETCH_DEVICES_REQUEST',
    FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
    FETCH_DEVICES_FAILURE: 'FETCH_DEVICES_FAILURE',

    ADD_DEVICE_REQUEST: 'ADD_DEVICE_REQUEST',
    ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
    ADD_DEVICE_FAILURE: 'ADD_DEVICE_FAILURE',

    GET_DEVICE_REQUEST: 'GET_DEVICE_REQUEST',
    GET_DEVICE_SUCCESS: 'GET_DEVICE_SUCCESS',
    GET_DEVICE_FAILURE: 'GET_DEVICE_FAILURE',

    GET_DEVICE_CODE_REQUEST: 'GET_DEVICE_CODE_REQUEST',
    GET_DEVICE_CODE_SUCCESS: 'GET_DEVICE_CODE_SUCCESS',
    GET_DEVICE_CODE_FAILURE: 'GET_DEVICE_CODE_FAILURE',

    GET_DEVICES_REQUEST: 'GET_DEVICES_REQUEST',
    GET_DEVICES_SUCCESS: 'GET_DEVICES_SUCCESS',
    GET_DEVICES_FAILURE: 'GET_DEVICES_FAILURE',

    EDIT_DEVICE_REQUEST: 'EDIT_DEVICE_REQUEST',
    EDIT_DEVICE_SUCCESS: 'EDIT_DEVICE_SUCCESS',
    EDIT_DEVICE_FAILURE: 'EDIT_DEVICE_FAILURE',
};